In [1]:
import pandas as pd
import numpy as np
import os
import time
import glob

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait

pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [91]:
directory = '/users/blaizelahman/Desktop/CFB Model/Updated Data'
pattern = os.path.join(directory, '*updated_model*.csv')

teamFiles = glob.glob(pattern)

teamDict = {}

for file in teamFiles:

    teamDF = pd.read_csv(file)

    if teamDF.shape[0] >= 56:
    
        key = teamDF['School'][0]
        teamDict[key] = teamDF
    
        print(f'Added: {key}')

Added: Western Michigan
Added: Memphis
Added: Arkansas
Added: Wake Forest
Added: Texas State
Added: Temple
Added: Auburn
Added: Miami
Added: Alabama
Added: Louisville
Added: Washington State
Added: North Texas
Added: Washington
Added: Virginia Tech
Added: Texas A&M
Added: Buffalo
Added: Ohio
Added: Minnesota
Added: Syracuse
Added: Southern Mississippi
Added: Ole Miss
Added: Idaho
Added: Western Kentucky
Added: Utah
Added: Stanford
Added: Georgia State
Added: Utah State
Added: West Virginia
Added: Nevada
Added: Louisiana
Added: Mississippi State
Added: Boston College
Added: Michigan State
Added: Miami (OH)
Added: Georgia Southern
Added: UT San Antonio
Added: Pittsburgh
Added: Nebraska
Added: Clemson
Added: Troy
Added: Arizona State
Added: Kent State
Added: UTEP
Added: Toledo
Added: UCLA
Added: Louisiana Monroe
Added: Oregon
Added: Oklahoma State
Added: Kansas State
Added: Middle Tennessee
Added: South Florida
Added: USC
Added: South Alabama
Added: Hawai'i
Added: Bowling Green
Added: Penn State
Added: Fresno State
Added: Boise State
Added: New Mexico State
Added: Navy
Added: Florida Atlantic
Added: Arizona
Added: South Carolina
Added: Virginia
Added: Rice
Added: Marshall
Added: Tulane
Added: Tulsa
Added: California
Added: UNLV
Added: Texas
Added: Georgia Tech
Added: Connecticut
Added: TCU
Added: Oregon State
Added: Maryland
Added: New Mexico
Added: Rutgers
Added: Wisconsin
Added: Iowa State
Added: Appalachian State
Added: Texas Tech
Added: Air Force
Added: NC State
Added: SMU
Added: San José State
Added: Colorado
Added: Florida
Added: Georgia
Added: UAB
Added: Central Michigan
Added: Louisiana Tech
Added: Eastern Michigan
Added: Baylor
Added: Iowa
Added: BYU
Added: Florida International
Added: Cincinnati
Added: Michigan
Added: Florida State
Added: Charlotte
Added: Wyoming
Added: Notre Dame
Added: Kansas
Added: Purdue
Added: LSU
Added: Ball State
Added: Arkansas State
Added: Vanderbilt
Added: Ohio State
Added: Indiana
Added: Duke
Added: Colorado State
Added: UMass
Added: Oklahoma
Added: Northwestern
Added: Northern Illinois
Added: Houston
Added: Kentucky
Added: UCF
Added: Missouri
Added: Old Dominion
Added: East Carolina
Added: Army
Added: Illinois
Added: North Carolina
Added: Akron
Added: San Diego State
Added: Tennessee

In [3]:
# setting the download directory and Chrome settings
directory = "/Users/blaizelahman/Desktop/CFBData"
chromeOptions = webdriver.ChromeOptions()
prefs = {"download.default_directory": directory}
chromeOptions.add_experimental_option("prefs", prefs)

# creating Chrome driver
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()), options = chromeOptions)

# making a dictionary to hold team betting data
bettingDict = {}

# downloading betting data for years 2035-2023 from collegefootballdata.com
for year in range(2013, 2024):

    # skipping 2020 because it has bad data
    if year == 2020: 
        continue
        
    try:
        url = f'https://collegefootballdata.com/exporter/lines?year={year}&seasonType=regular'
        driver.get(url)
        time.sleep(4) 
            
        # clicking the query button
        query = driver.find_element(By.XPATH, "//button[contains(span/text(), 'Query')]")
        query.click()
        time.sleep(3) 
            
        # clicking the export button
        export = driver.find_element(By.XPATH, "//button[contains(span/text(), 'Export')]")
        export.click()
        time.sleep(3)

        key = str(year)

            
        # grabs files from CFBData folder
        files = os.listdir(directory)
        
        # grab the file paths for all files ending in .csv
        filePaths = [os.path.join(directory, name) for name in files if name.endswith('.csv')]

        # grabbing the most recently made file out of those in paths
        file = max(filePaths, key=os.path.getctime)
            
        # loading csv file
        bettingDict[key] = pd.read_csv(file)

        # deleting the file after it has been added
        os.remove(file)

    except Exception as e:
        print(f'Cannot grab data for {year}. Error: {e}')

    print(f'Successfully grabbed data for {year}')

driver.quit()

Successfully grabbed data for 2013
Successfully grabbed data for 2014
Successfully grabbed data for 2015
Successfully grabbed data for 2016
Successfully grabbed data for 2017
Successfully grabbed data for 2018
Successfully grabbed data for 2019
Successfully grabbed data for 2021
Successfully grabbed data for 2022
Successfully grabbed data for 2023

In [92]:
# setting our preferred line providers
lineProviders = ['DraftKings', 'consensus', 'Bovada']

# combining betting dataframes
combinedBetting = pd.concat(bettingDict.values(), ignore_index = True)

# function to get line from most preferred available line
def getPreferredLine(group):

    # go through preferred lines and if our preferred providers are there, return the line
    for provider in lineProviders:
        preferredLine = group[group['LineProvider'] == provider]

        # if preferred line provider has line, return
        if not preferredLine.empty:
            return preferredLine.iloc[0]

    # returning first available line if none of our preferred ones are available
    return group.iloc[0] 

# getting the preferred line for each individual game
preferredLines = combinedBetting.groupby('Id').apply(lambda x: getPreferredLine(x)).reset_index(drop = True)

# merging the preferred lines with each dataframe in teamDict
for team, teamDF in teamDict.items():
    
    # merging based on Game Id
    teamDict[team] = teamDF.merge(preferredLines, left_on = 'Game Id', right_on = 'Id', how = 'left')

In [93]:
teamDict['Florida State'][teamDict['Florida State']['Year'] == 2023]

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Game Id,School,Conference,HomeAway,Points,Week,Year,completionAttempts,defensiveTDs,firstDowns,fourthDownEff,fumblesLost,fumblesRecovered,interceptionTDs,interceptionYards,interceptions,kickReturnTDs,kickReturnYards,kickReturns,kickingPoints,netPassingYards,passesDeflected,passesIntercepted,passingTDs,possessionTime,puntReturnTDs,puntReturnYards,puntReturns,qbHurries,rushingAttempts,rushingTDs,rushingYards,sacks,tackles,tacklesForLoss,thirdDownEff,totalFumbles,totalPenaltiesYards,totalYards,turnovers,yardsPerPass,yardsPerRushAttempt,totalTDs,School_opp,Conference_opp,HomeAway_opp,Points_opp,Week_opp,Year_opp,completionAttempts_opp,defensiveTDs_opp,firstDowns_opp,fourthDownEff_opp,fumblesLost_opp,fumblesRecovered_opp,interceptionTDs_opp,interceptionYards_opp,interceptions_opp,kickReturnTDs_opp,kickReturnYards_opp,kickReturns_opp,kickingPoints_opp,netPassingYards_opp,passesDeflected_opp,passesIntercepted_opp,passingTDs_opp,possessionTime_opp,puntReturnTDs_opp,puntReturnYards_opp,puntReturns_opp,qbHurries_opp,rushingAttempts_opp,rushingTDs_opp,rushingYards_opp,sacks_opp,tackles_opp,tacklesForLoss_opp,thirdDownEff_opp,totalFumbles_opp,totalPenaltiesYards_opp,totalYards_opp,turnovers_opp,yardsPerPass_opp,yardsPerRushAttempt_opp,totalTDs_opp,scoreDiff,pointTotal,Win,rolling_sum_Points20,rolling_sum_firstDowns20,rolling_sum_fumblesLost20,rolling_sum_fumblesRecovered20,rolling_sum_interceptions20,rolling_sum_kickReturnYards20,rolling_sum_kickingPoints20,rolling_sum_netPassingYards20,rolling_sum_passesDeflected20,rolling_sum_passesIntercepted20,rolling_sum_passingTDs20,rolling_sum_puntReturns20,rolling_sum_qbHurries20,rolling_sum_rushingAttempts20,rolling_sum_rushingTDs20,rolling_sum_rushingYards20,rolling_sum_sacks20,rolling_sum_tacklesForLoss20,rolling_sum_totalFumbles20,rolling_sum_totalPenaltiesYards20,rolling_sum_totalYards20,rolling_sum_turnovers20,rolling_sum_yardsPerPass20,rolling_sum_yardsPerRushAttempt20,rolling_sum_totalTDs20,rolling_sum_Points8,rolling_sum_firstDowns8,rolling_sum_fumblesLost8,rolling_sum_fumblesRecovered8,rolling_sum_interceptions8,rolling_sum_kickReturnYards8,rolling_sum_kickingPoints8,rolling_sum_netPassingYards8,rolling_sum_passesDeflected8,rolling_sum_passesIntercepted8,rolling_sum_passingTDs8,rolling_sum_puntReturns8,rolling_sum_qbHurries8,rolling_sum_rushingAttempts8,rolling_sum_rushingTDs8,rolling_sum_rushingYards8,rolling_sum_sacks8,rolling_sum_tacklesForLoss8,rolling_sum_totalFumbles8,rolling_sum_totalPenaltiesYards8,rolling_sum_totalYards8,rolling_sum_turnovers8,rolling_sum_yardsPerPass8,rolling_sum_yardsPerRushAttempt8,rolling_sum_totalTDs8,rolling_sum_Points20_opp,rolling_sum_firstDowns20_opp,rolling_sum_fumblesLost20_opp,rolling_sum_fumblesRecovered20_opp,rolling_sum_interceptions20_opp,rolling_sum_kickReturnYards20_opp,rolling_sum_kickingPoints20_opp,rolling_sum_netPassingYards20_opp,rolling_sum_passesDeflected20_opp,rolling_sum_passesIntercepted20_opp,rolling_sum_passingTDs20_opp,rolling_sum_puntReturns20_opp,rolling_sum_qbHurries20_opp,rolling_sum_rushingAttempts20_opp,rolling_sum_rushingTDs20_opp,rolling_sum_rushingYards20_opp,rolling_sum_sacks20_opp,rolling_sum_tacklesForLoss20_opp,rolling_sum_totalFumbles20_opp,rolling_sum_totalPenaltiesYards20_opp,rolling_sum_totalYards20_opp,rolling_sum_turnovers20_opp,rolling_sum_yardsPerPass20_opp,rolling_sum_yardsPerRushAttempt20_opp,rolling_sum_totalTDs20_opp,rolling_sum_Points8_opp,rolling_sum_firstDowns8_opp,rolling_sum_fumblesLost8_opp,rolling_sum_fumblesRecovered8_opp,rolling_sum_interceptions8_opp,rolling_sum_kickReturnYards8_opp,rolling_sum_kickingPoints8_opp,rolling_sum_netPassingYards8_opp,rolling_sum_passesDeflected8_opp,rolling_sum_passesIntercepted8_opp,rolling_sum_passingTDs8_opp,rolling_sum_puntReturns8_opp,rolling_sum_qbHurries8_opp,rolling_sum_rushingAttempts8_opp,rolling_sum_rushingTDs8_opp,rolling_sum_rushingYards8_opp,rolling_sum_sacks8_opp,rolling_sum_tacklesForLoss8_opp,rolling_sum_totalFumbles8_opp,rolling_sum_totalPenaltiesYards8_opp,rolling_sum_totalYards8_opp,rolling_sum_turnovers8_opp,rolling_sum_yardsPerPass8_opp,rolling_sum_yardsPerRushAttempt8_opp,rolling_sum_totalTDs8_opp,talent,talent_opp,SP,SP_opp,Id,HomeTeam,HomeScore,AwayTeam,AwayScore,LineProvider,OverUnder,Spread,FormattedSpread,OpeningSpread,OpeningOverUnder,HomeMoneyline,AwayMoneyline
175,175,195,861,401520182,Florida State,ACC,home,45,1,2023,24.32,0.0,22.0,1.1,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,9.0,359.0,4.0,1.0,4.0,35.23,NaN,NaN,NaN,1.0,34.0,2.0,135.0,4.0,33.0,5.0,9.14,0.0,7.640,494.0,1.0,11.2,4.0,6.0,LSU,SEC,away,24,1,2023,22.37,0.0,23.0,0.3,1.0,0.0,0.0,2.0,1.0,0.0,51.0,4.0,6.0,346.0,2.0,1.0,1.0,24.37,0.0,0.3,1.0,4.0,27.0,2.0,113.0,0.0,27.0,4.0,3.10,1.0,2.300,459.0,2.0,9.4,4.2,3.0,21,69,True,673.0,457.0,13.0,14.0,10.0,653.0,133.0,4728.0,70.0,20.0,40.0,35.0,56.0,771.0,46.0,3986.0,53.0,129.0,28.0,144.234,8714.0,23.0,8.770,5.050,88.0,284.0,191.0,6.0,5.0,3.0,175.0,54.0,1986.0,28.0,5.0,19.0,17.0,23.0,311.0,19.0,1707.0,23.0,51.0,13.0,62.264,3693.0,9.0,8.5500,5.5625,38.0,591.0,458.0,17.0,20.0,12.0,470.0,125.0,5140.0,61.0,12.0,32.0,29.0,52.0,749.0,42.0,3274.0,44.0,110.0,23.0,113.980,8414.0,29.0,7.430,4.280,76.0,253.0,202.0,7.0,5.0,4.0,211.0,53.0,2209.0,28.0,3.0,12.0,7.0,30.0,291.0,21.0,1427.0,12.0,34.0,8.0,43.590,3636.0,11.0,8.1750,4.7750,33.0,765.33,899.31,19.4,19.1,401520182.0,Florida State,45.0,LSU,24.0,DraftKings,56.5,2.5,LSU -2.5,2.5,55.5,110.0,-135.0
176,176,196,865,401525493,Florida State,ACC,home,66,2,2023,18.32,0.0,26.0,4.5,0.0,0.0,1.0,30.0,0.0,0.0,66.0,3.0,12.0,248.0,5.0,1.0,4.0,32.33,0.0,21.0,3.0,0.0,37.0,4.0,306.0,2.0,2.0,2.0,4.12,NaN,3.450,554.0,0.0,7.8,8.3,9.0,Southern Mississippi,Sun Belt,away,13,2,2023,11.34,0.0,18.0,0.1,0.0,0.0,NaN,NaN,1.0,0.0,82.0,4.0,7.0,154.0,7.0,NaN,0.0,27.19,NaN,NaN,NaN,0.0,28.0,1.0,104.0,2.0,2.0,1.0,3.13,NaN,13.900,258.0,1.0,4.5,3.7,1.0,53,79,True,685.0,457.0,12.0,15.0,10.0,614.0,133.0,4956.0,71.0,20.0,42.0,31.0,56.0,768.0,46.0,3874.0,56.0,131.0,26.0,148.574,8830.0,22.0,9.125,4.915,90.0,308.0,192.0,5.0,6.0,4.0,63.0,62.0,2064.0,29.0,6.0,20.0,16.0,20.0,317.0,21.0,1730.0,23.0,47.0,10.0,57.944,3794.0,9.0,8.9500,5.5625,41.0,457.0,341.0,19.0,15.0,23.0,894.0,129.0,3575.0,64.0,25.0,27.0,33.0,50.0,747.0,20.0,2611.0,52.0,136.0,29.0,156.800,6186.0,42.0,7.515,3.315,53.0,189.0,153.0,4.0,5.0,7.0,283.0,67.0,1687.0,25.0,10.0,11.0,10.0,17.0,298.0,8.0,982.0,19.0,55.0,9.0,58.490,2669.0,11.0,7.7250,3.1625,20.0,765.33,425.21,19.4,-14.4,401525493.0,Florida State,66.0,Southern Mississippi,13.0,DraftKings,54.0,-31.0,Florida State -31,-31.0,53.5,-8000.0,2200.0
177,177,197,870,401525500,Florida State,ACC,away,31,3,2023,15.24,0.0,20.0,1.1,2.0,0.0,0.0,0.0,0.0,0.0,39.0,3.0,7.0,212.0,4.0,1.0,2.0,26.10,0.0,0.4,2.0,0.0,34.0,2.0,128.0,2.0,44.0,10.0,1.90,3.0,5.450,340.0,2.0,8.8,3.8,4.0,Boston College,ACC,home,29,3,2023,20.34,0.0,20.0,4.5,0.0,1.0,NaN,NaN,1.0,0.0,36.0,2.0,5.0,305.0,1.0,NaN,1.0,33.50,NaN,NaN,NaN,2.0,41.0,2.0,152.0,0.0,27.0,1.0,8.19,0.0,18.131,457.0,1.0,9.0,3.7,3.0,2,60,True,716.0,461.0,12.0,15.0,10.0,626.0,140.0,5059.0,70.0,20.0,43.0,34.0,54.0,764.0,48.0,3942.0,57.0,129.0,26.0,146.524,9001.0,22.0,8.955,5.040,94.0,357.0,203.0,5.0,6.0,2.0,116.0,69.0,2131.0,31.0,6.0,23.0,18.0,16.0,326.0,24.0,1830.0,24.0,42.0,10.0,51.294,3961.0,7.0,9.1750,5.6750,48.0,394.0,357.0,14.0,16.0,20.0,1071.0,100.0,4408.0,65.0,9.0,30.0,20.0,49.0,689.0,18.0,2102.1,40.0,122.0,32.0,145.804,6509.0,34.0,7.135,2.885,48.0,162.0,151.0,7.0,9.0,10.0,367.0,36.0,1962.0,22.0,1.0,14.0,8.0,15.0,267.0,6.0,796.1,15.0,53.0,14.0,70.630,2757.0,17.0,6.8750,2.8375,20.0,765.33,650.23,19.4,-5.9,401525500.0,Boston College,29.0,Florida State,31.0,Bovada,47.5,25.0,Florida State -25.0,28.5,56.5,1600.0,-10000.0
178,178,198,874,401525507,Florida State,ACC,away,31,4,2023,21.37,0.0,16.0,1.2,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,7.0,289.0,7.0,NaN,2.0,25.24,0.0,9.0,1.0,1.0,20.0,1.0,22.0,3.0,43.0,6.0,4.13,0.0,7.600,311.0,0.0,7.8,1.1,3.0,Clemson,ACC,home,24,4,2023,25.38,0.0,25.0,1.2,1.0,0.0,NaN,NaN,0.0,0.0,46.0,2.0,6.0,283.0,5.0,NaN,1.0,34.36,0.0,21.0,2.0,3.0,41.0,2.0,146.0,2.0,21.0,5.0,6.14,2.0,6.500,429.0,1.0,7.4,3.6,3.0,7,55,True,688.0,456.0,13.0,14.0,10.0,639.0,136.0,5050.0,71.0,19.0,43.0,35.0,52.0,753.0,45.0,3705.0,55.0,130.0,27.0,148.564,8755.0,23.0,8.660,4.825,90.0,360.0,195.0,6.0,6.0,2.0,141.0,72.0,2089.0,32.0,7.0,23.0,18.0,15.0,326.0,24.0,1752.0,23.0,48.0,12.0,53.574,3841.0,8.0,9.5250,5.3875,48.0,718.0,463.0,20.0,16.0,13.0,560.0,168.0,4684.0,96.0,22.0,38.0,42.0,81.0,798.0,48.0,3856.0,59.0,151.5,32.0,110.290,8540.0,33.0,6.970,4.770,90.0,285.0,197.0,12.0,7.0,4.0,204.0,51.0,1948.0,32.0,10.0,15.0,19.0,32.0,307.0,19.0,1556.0,22.0,57.5,16.0,33.980,3504.0,16.0,6.6875,4.9625,38.0,765.33,917.88,19.4,10.5,401525507.0,Clemson,24.0,Florida State,31.0,DraftKings,55.0,2.0,Florida State -2,-3.0,NaN,110.0,-130.0
179,179,199,877,401525518,Florida State,ACC,home,39,6,2023,18.25,0.0,20.0,1.1,0.0,1.0,NaN,NaN,0.0,NaN,NaN,NaN,7.0,170.0,5.0,NaN,2.0,28.44,0.0,33.0,2.0,2.0,36.0,3.0,282.0,2.0,30.0,5.0,5.12,0.0,12.990,452.0,0.0,6.8,7.8,5.0,Virginia Tech,ACC,away,17,6,2023,14.27,1.0,19.0,3.4,1.0,0.0,NaN,NaN,0.0,1.0,156.0,4.0,5.0,104.0,3.0,NaN,0.0,31.16,0.0,8.0,1.0,1.0,35.0,1.0,209.0,2.0,22.0,4.0,2.13,3.0,6.600,313.0,1.0,3.9,6.0,2.0,22,56,True,699.0,460.0,11.0,12.0,10.0,613.0,141.0,5163.0,76.0,18.0,43.0,35.0,48.0,739.0,46.0,3662.0,55.0,125.0,24.0,146.314,8825.0,21.0,8.650,4.785,91.0,350.0,180.0,4.0,7.0,2.0,105.0,68.0,1982.0,36.0,7.0,22.0,16.0,13.0,303.0,23.0,1528.0,22.0,44.0,9.0,48.070,3510.0,6.0,9.2250,4.8125,46.0,456.0,369.0,12.0,16.0,13.0,954.0,116.0,4015.0,69.0,8.0,26.0,41.0,57.0,747.0,25.0,2915.0,44.0,127.0,24.0,157.478,6930.0,25.0,7.200,3.760,55.0,171.0,147.0,4.0,7.0,4.0,470.0,43.0,1540.0,20.0,4.0,10.0,13.0,17.0,313.0,10.0,1121.0,20.0,52.0,10.0,47.040,2661.0,8.0,6.9375,3.6000,21.0,765.33,638.89,19.4,5.8,401525518.0,Florida State,39.0,Virginia Tech,17.0,DraftKings,53.0,-24.0,Florida State -24,-25.5,53.0,-2400.0,1100.0
180,180,200,881,401525524,Florida State,ACC,home,41,7,2023,25.39,0.0,22.0,0.2,0.0,1.0,0.0,13.0,0.0,NaN,NaN,NaN,11.0,344.0,9.0,1.0,2.0,27.01,0.0,107.0,6.0,3.0,34.0,3.0,191.0,3.0,34.0,6.0,9.17,2.0,6.500,535.0,0.0,8.8,5.6,5.0,Syracuse,ACC,away,3,7,2023,12.31,0.0,12.0,1.2,1.0,0.0,NaN,NaN,1.0,NaN,NaN,NaN,3.0,137.0,5.0,NaN,0.0,32.59,0.0,5.0,1.0,3.0,36.0,0.0,124.0,2.0,41.0,4.0,6.19,1.0,2.800,261.0,2.0,4.4,3.4,0.0,38,44,True,724.0,462.0,11.0,13.0,9.0,593.0,146.0,5100.0,79.0,17.0,44.0,35.0,46.0,748.0,48.0,3906.0,54.0,124.0,23.0,157.184,9006.0,20.0,8.725,5.105,94.0,344.0,178.0,4.0,4.0,1.0,105.0,66.0,1927.0,39.0,5.0,21.0,17.0,14.0,290.0,23.0,1581.0,21.0,45.0,9.0,56.660,3508.0,5.0,8.3125,5.2000,45.0,555.0,394.0,10.0,18.0,15.0,584.0,139.0,4528.0,53.0,17.0,32.0,44.0,66.0,707.0,32.0,2907.0,52.0,131.0,23.0,174.792,7435.0,25.0,8.090,3.960,68.0,233.0,167.0,6.0,8.0,7.0,128.0,53.0,1915.0,26.0,6.0,13.0,19.0,24.0,306.0,15.0,1327.0,23.0,58.0,12.0,68.235,3242.0,13.0,7.8000,4.2000,30.0,765.33,610.75,19.4,-4.4,401525524.0,Florida State,41.0,Syracuse,3.0,DraftKings,53.5,-18.5,Florida State -18.5,-17.5,56.5,-1100.0,675.0
181,181,201,886,401525530,Florida State,ACC,home,38,8,2023,27.36,1.0,24.0,0.2,0.0,0.0,0.0,0.0,1.0,1.0,141.0,3.0,8.0,268.0,3.0,1.0,2.0,30.48,0.0,8.0,3.0,8.0,32.0,2.0,152.0,0.0,27.0,4.0,7.12,1.0,8.500,420.0,1.0,7.4,4.8,5.0,Duke,ACC,away,20,8,2023,8.22,1.0,15.0,0.2,0.0,0.0,1.0,13.0,1.0,0.0,82.0,3.0,8.0,76.0,2.0,1.0,0.0,29.12,NaN,NaN,NaN,2.0,35.0,1.0,197.0,1.0,28.0,5.0,4.12,NaN,7.530,273.0,1.0,3.5,5.6,2.0,18,58,True,734.0,460.0,10.0,13.0,9.0,593.0,146.0,5170.0,80.0,16.0,46.0,39.0,48.0,734.0,48.0,3937.0,54.0,124.0,23.0,155.084,9107.0,19.0,8.640,5.220,96.0,347.0,175.0,3.0,5.0,1.0,105.0,69.0,2081.0,47.0,5.0,19.0,18.0,15.0,284.0,25.0,1542.0,21.0,43.0,9.0,54.410,3623.0,4.0,8.6500,5.1750,45.0,614.0,409.0,8.0,22.0,10.0,957.0,144.0,4207.0,89.0,15.0,26.0,23.0,70.0,725.0,46.0,3661.0,45.0,102.0,17.0,118.870,7868.0,18.0,7.565,4.960,76.0,241.0,160.0,4.0,4.0,4.0,283.0,59.0,1604.0,38.0,7.0,10.0,10.0,26.0,277.0,18.0,1498.0,18.0,41.0,5.0,43.030,3102.0,8.0,7.8000,5.3125,29.0,765.33,620.90,19.4,9.4,401525530.0,Florida State,38.0,Duke,20.0,DraftKings,49.5,-14.5,Florida State -14.5,-15.5,49.0,-600.0,440.0
182,182,202,889,401525536,Florida State,ACC,away,41,9,2023,23.36,0.0,20.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,68.0,2.0,11.0,382.0,6.0,NaN,3.0,30.36,0.0,24.0,3.0,0.0,30.0,2.0,126.0,6.0,39.0,10.0,7.14,1.0,9.115,508.0,0.0,10.6,4.2,5.0,Wake Forest,ACC,home,16,9,2023,6.16,0.0,15.0,0.1,0.0,0.0,NaN,NaN,0.0,0.0,60.0,3.0,4.0,82.0,4.0,NaN,0.0,29.24,0.0,12.0,2.0,5.0,49.0,2.0,128.0,1.0,39.0,4.0,3.14,NaN,5.440,210.0,0.0,5.1,2.6,2.0,25,57,True,746.0,462.0,10.0,13.0,10.0,672.0,148.0,5187.0,80.0,16.0,45.0,41.0,48.0,735.0,50.0,3975.0,50.0,117.0,24.0,150.464,9162.0,20.0,8.640,5.275,98.0,336.0,176.0,3.0,4.0,2.0,246.0,70.0,2160.0,41.0,6.0,19.0,19.0,19.0,271.0,22.0,1443.0,17.0,41.0,8.0,58.510,3603.0,5.0,8.4500,5.0750,43.0,620.0,483.0,13.0,16.0,21.0,706.0,150.0,5371.0,81.0,13.0,50.0,32.0,80.0,808.0,24.0,2752.0,46.0,126.0,27.0,96.090,8123.0,34.0,8.125,3.250,77.0,178.0,176.0,7.0,5.0,9.0,367.0,58.0,1596.0,25.0,6.0,10.0,14.0,30.0,338.0,8.0,1144.0,18.0,49.0,14.0,34.920,2740.0,16.0,6.8875,3.2375,19.0,765.33,603.68,19.4,-7.9,401525536.0,Wake Forest,16.0,Florida State,41.0,DraftKings,51.0,20.5,Florida State -20.5,20.0,53.0,850.0,-1450.0
183,183,203,893,401525541,Florida State,ACC,away,24,10,2023,23.37,0.0,22.0,0.1,1.0,2.0,0.0,2.0,0.0,NaN,NaN,NaN,6.0,363.0,6.0,1.0,1.0,34.54,0.0,0.2,1.0,6.0,37.0,2.0,138.0,3.0,24.0,3.0,5.14,2.0,6.600,501.0,1.0,9.8,3.7,3.0,Pittsburgh,ACC,home,7,10,2023,15.36,0.0,16.0,1.1,2.0,1.0,NaN,NaN,1.0,0.0,15.0,1.0,1.0,244.0,5.0,NaN,1.0,25.06,NaN,NaN,NaN,4.0,24.0,0.0,89.0,2.0,38.0,11.0,0.11,3.0,11.910,333.0,3.0,6.8,3.7,1.0,17,31,True,766.0,459.0,9.0,13.0,8.0,674.0,156.0,5366.0,85.0,13.0,47.0,43.0,43.0,732.0,50.0,3956.0,55.0,121.0,21.0,149.689,9322.0,17.0,8.860,5.265,100.0,332.0,170.0,2.0,4.0,2.0,314.0,72.0,2272.0,43.0,5.0,21.0,20.0,15.0,257.0,19.0,1342.0,22.0,48.0,7.0,61.245,3614.0,4.0,8.6500,4.9500,42.0,518.0,380.0,14.0,17.0,20.0,797.1,124.0,4252.0,80.0,16.0,24.0,51.0,71.0,707.0,33.0,3022.0,65.0,140.0,37.0,172.641,7274.0,34.0,7.370,4.115,63.0,141.0,117.0,6.0,4.0,10.0,402.1,33.0,1637.0,23.0,7.0,11.0,15.0,24.0,225.0,4.0,706.0,20.0,62.0,11.0,75.851,2343.0,16.0,6.7250,3.1000,17.0,765.33,700.42,19.4,-7.3,401525541.0,Pittsburgh,7.0,Florida State,24.0,DraftKings,50.0,21.5,Florida State -21.5,23.0,NaN,800.0,-1350.0
184,184,204,897,401525550,Florida State,ACC,home,27,11,2023,19.31,0.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,1.0,9.0,265.0,8.0,1.0,1.0,30.40,0.0,62.0,3.0,3.0,31.0,2.0,57.0,2.0,25.0,7.0,3.12,1.0,3.350,322.0,0.0,8.5,1.8,3.0,Miami,ACC,away,20,11,2023,10.30,0.0,13.0,1.2,0.0,0.0,NaN,NaN,1.0,0.0,37.0,2.0,8.0,204.0,0.0,NaN,2.0,29.20,0.0,16.0,1.0,2.0,34.0,0.0,131.0,3.0,33.0,9.0,4.16,NaN,7.400,335.0,1.0,6.8,3.9,2.0,7,47,True,766.0,458.0,9.0,13.0,8.0,629.0,156.0,5469.0,89.0,14.0,46.0,43.0,49.0,731.0,51.0,3962.0,54.0,118.0,23.0,149.639,9431.0,17.0,8.955,5.275,100.0,311.0,170.0,3.0,5.0,1.0,314.0,69.0,2276.0,45.0,5.0,18.0,21.0,20.0,260.0,19.0,1345.0,21.0,46.0,9.0,60.205,3621.0,4.0,8.4750,4.9125,39.0,492.0,414.0,19.0,16.0,24.0,1379.0,150.0,4876.0,58.0,19.0,34.0,21.0,45.0,665.0,18.0,2778.0,64.0,142.0,24.0,146.784,7654.0,43.0,6.965,4.015,56.0,223.0,173.0,6.0,5.0,12.0,483.0,65.0,1939.0,18.0,7.0,13.0,7.0,27.0,282.0,12.0,1393.0,29.0,61.0,8.0,52.530,3332.0,18.0,7.0625,4.8500,26.0,765.33,860.27,19.4,9.6,401525550.0,Florida State,27.0,Miami,20.0,DraftKings,NaN,-14.0,Florida State -14,-15.0,NaN,-625.0,455.0
185,185,205,901,401525556,Florida State,ACC,home,58,12,2023,17.30,1.0,26.0,0.2,0.0,1.0,0.0,2.0,0.0,NaN,NaN,NaN,10.0,273.0,4.0,1.0,2.0,28.18,0.0,6.0,1.0,3.0,37.0,5.0,248.0,5.0,33.0,11.0,4.11,1.0,8.830,521.0,0.0,9.1,6.7,7.0,North Alabama,UAC,away,13,12,2023,15.30,0.0,14.0,1.1,1.0,0.0,NaN,NaN,1.0,NaN,NaN,NaN,1.0,83.0,2.0,NaN,2.0,31.42,0.0,3.0,2.0,7.0,34.0,0.0,143.0,2.0,35.0,5.0,3.16,3.0,8.750,226.0,2.0,2.8,4.2,2.0,45,71,True,746.0,442.0,9.0,13.0,7.0,624.0,154.0,5502.0,92.0,15.0,47.0,44.0,52.0,708.0,47.0,3613.0,55.0,119.0,23.0,147.439,9115.0,16.0,8.855,4.990,97.0,272.0,161.0,3.0,5.0,1.0,269.0,66.0,2293.0,48.0,5.0,15.0,21.0,23.0,254.0,17.0,1096.0,21.0,51.0,10.0,60.105,3389.0,4.0,8.5625,4.1000,33.0,503.0,410.0,16.0,12.0,24.0,554.0,83.0,4500.0,5.0,11.0,41.0,17.0,7.0,750.0,26.0,3439.0,4.0,9.0,26.0,139.681,7939.0,40.0,6.765,4.380,68.0,173.0,161.0,6.0,4.0,12.0,121.0,23.0,1800.0,2.0,6.0,19.0,9.0,7.0,299.0,4.0,1164.0,2.0,5.0,10.0,62.281,2964.0,18.0,5.8875,3.6750,24.0,765.33,163.24,19.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,186,206,906,401520429,Florida State,ACC,away,24,13,2023,12.26,0.0,16.0,1.1,0.0,0.0,0.0,6.0,0.0,0.0,17.0,1.0,6.0,134.0,2.0,1.0,0.0,25.08,0.0,34.0,1.0,4.0,31.0,3.0,90.0,6.0,33.0,11.0,4.14,NaN,5.220,224.0,0.0,5.2,2.9,3.0,Florida,SEC,home,15,13,2023,9.16,0.0,13.0,0.1,0.0,0.0,NaN,NaN,1.0,0.0,29.0,1.0,7.0,86.0,8.0,NaN,0.0,34.52,NaN,NaN,NaN,6.0,44.0,1.0,146.0,3.0,23.0,7.0,7.16,2.0,8.900,232.0,1.0,5.4,3.3,1.0,9,39,True,769.0,447.0,9.0,12.0,5.0,603.0,159.0,5509.0,92.0,15.0,45.0,43.0,52.0,708.0,51.0,3672.0,58.0,126.0,24.0,149.879,9181.0,14.0,8.815,5.070,99.0,299.0,167.0,1.0,6.0,1.0,230.0,69.0,2354.0,48.0,5.0,15.0,20.0,26.0,257.0,20.0,1216.0,24.0,52.0,8.0,63.485,3570.0,2.0,8.6000,4.4625,36.0,613.0,423.0,10.0,18.0,9.0,631.0,149.0,4940.0,59.0,8.0,36.0,29.0,71.0,720.0,39.0,3606.0,37.0,110.0,23.0,141.480,8546.0,19.0,8.110,4.805,76.0,230.0,167.0,4.0,4.0,4.0,245.0,58.0,2095.0,27.0,2.0,16.0,6.0,29.0,271.0,12.0,1160.0,15.0,39.0,9.0,60.640,3255.0,8.0,7.5000,4.2750,28.0,765.33,845.29,19.4,6.8,401520429.0,Florida,15.0,Florida State,24.0,DraftKings,51.0,6.0,Florida State -6,9.0,NaN,185.0,-225.0
187,187,207,909,401539478,Florida State,ACC,home,16,14,2023,8.21,0.0,12.0,0.1,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,10.0,55.0,10.0,1.0,0.0,31.28,NaN,NaN,NaN,6.0,44.0,1.0,164.0,7.0,33.0,14.0,2.16,1.0,3.200,219.0,0.0,2.6,3.7,1.0,Louisville,ACC,away,6,14,2023,14.36,0.0,10.0,0.3,0.0,0.0,NaN,NaN,1.0,0.0,16.0,1.0,6.0,111.0,4.0,NaN,0.0,28.32,0.0,0.0,1.0,3.0,34.0,0.0,77.0,4.0,25.0,7.0,3.18,1.0,5.480,188.0,1.0,3.1,2.3,0.0,10,22,True,749.0,442.0,9.0,12.0,5.0,527.0,157.0,5293.0,91.0,14.0,44.0,43.0,54.0,704.0,50.0,3582.0,61.0,131.0,24.0,147.509,8875.0,14.0,8.510,4.960,96.0,292.0,167.0,1.0,5.0,1.0,247.0,68.0,2199.0,43.0,6.0,13.0,20.0,29.0,268.0,22.0,1284.0,27.0,57.0,8.0,61.105,3483.0,2.0,8.2750,4.6875,36.0,596.0,400.0,9.0,20.0,18.0,481.0,156.0,4607.0,63.0,21.0,31.0,45.0,63.0,753.0,37.0,3560.0,57.0,124.0,25.0,129.120,8167.0,27.0,8.365,4.645,72.0,217.0,160.0,4.0,3.0,6.0,272.0,59.0,1667.0,25.0,7.0,10.0,17.0,21.0,301.0,15.0,1310.0,25.0,51.0,12.0,43.530,2977.0,10.0,7.3750,4.3250,26.0,765.33,744.16,19.4,8.0,401539478.0,Florida State,16.0,Louisville,6.0,DraftKings,51.0,-3.5,Florida State -3.5,-3.5,51.0,-102.0,-118.0

In [94]:
def correctSpread(row, team):
    if row['HomeTeam'] == team:
        row['Spread'] = float(row['Spread']) * -1
    return row

In [95]:
for team, teamDF in teamDict.items(): 
    
    teamDict[team] = teamDF.apply(correctSpread, axis = 1, team = team)

In [101]:
teamDict['TCU'][teamDict['TCU']['Year'] == 2023]

,Game Id,School,Conference,HomeAway,Points,Week,Year,completionAttempts,defensiveTDs,firstDowns,fourthDownEff,fumblesLost,fumblesRecovered,interceptionTDs,interceptionYards,interceptions,kickReturnTDs,kickReturnYards,kickReturns,kickingPoints,netPassingYards,passesDeflected,passesIntercepted,passingTDs,possessionTime,puntReturnTDs,puntReturnYards,puntReturns,qbHurries,rushingAttempts,rushingTDs,rushingYards,sacks,tackles,tacklesForLoss,thirdDownEff,totalFumbles,totalPenaltiesYards,totalYards,turnovers,yardsPerPass,yardsPerRushAttempt,totalTDs,School_opp,Conference_opp,HomeAway_opp,Points_opp,Week_opp,Year_opp,completionAttempts_opp,defensiveTDs_opp,firstDowns_opp,fourthDownEff_opp,fumblesLost_opp,fumblesRecovered_opp,interceptionTDs_opp,interceptionYards_opp,interceptions_opp,kickReturnTDs_opp,kickReturnYards_opp,kickReturns_opp,kickingPoints_opp,netPassingYards_opp,passesDeflected_opp,passesIntercepted_opp,passingTDs_opp,possessionTime_opp,puntReturnTDs_opp,puntReturnYards_opp,puntReturns_opp,qbHurries_opp,rushingAttempts_opp,rushingTDs_opp,rushingYards_opp,sacks_opp,tackles_opp,tacklesForLoss_opp,thirdDownEff_opp,totalFumbles_opp,totalPenaltiesYards_opp,totalYards_opp,turnovers_opp,yardsPerPass_opp,yardsPerRushAttempt_opp,totalTDs_opp,scoreDiff,pointTotal,Win,rolling_sum_Points20,rolling_sum_firstDowns20,rolling_sum_fumblesLost20,rolling_sum_fumblesRecovered20,rolling_sum_interceptions20,rolling_sum_kickReturnYards20,rolling_sum_kickingPoints20,rolling_sum_netPassingYards20,rolling_sum_passesDeflected20,rolling_sum_passesIntercepted20,rolling_sum_passingTDs20,rolling_sum_puntReturns20,rolling_sum_qbHurries20,rolling_sum_rushingAttempts20,rolling_sum_rushingTDs20,rolling_sum_rushingYards20,rolling_sum_sacks20,rolling_sum_tacklesForLoss20,rolling_sum_totalFumbles20,rolling_sum_totalPenaltiesYards20,rolling_sum_totalYards20,rolling_sum_turnovers20,rolling_sum_yardsPerPass20,rolling_sum_yardsPerRushAttempt20,rolling_sum_totalTDs20,rolling_sum_Points8,rolling_sum_firstDowns8,rolling_sum_fumblesLost8,rolling_sum_fumblesRecovered8,rolling_sum_interceptions8,rolling_sum_kickReturnYards8,rolling_sum_kickingPoints8,rolling_sum_netPassingYards8,rolling_sum_passesDeflected8,rolling_sum_passesIntercepted8,rolling_sum_passingTDs8,rolling_sum_puntReturns8,rolling_sum_qbHurries8,rolling_sum_rushingAttempts8,rolling_sum_rushingTDs8,rolling_sum_rushingYards8,rolling_sum_sacks8,rolling_sum_tacklesForLoss8,rolling_sum_totalFumbles8,rolling_sum_totalPenaltiesYards8,rolling_sum_totalYards8,rolling_sum_turnovers8,rolling_sum_yardsPerPass8,rolling_sum_yardsPerRushAttempt8,rolling_sum_totalTDs8,rolling_sum_Points20_opp,rolling_sum_firstDowns20_opp,rolling_sum_fumblesLost20_opp,rolling_sum_fumblesRecovered20_opp,rolling_sum_interceptions20_opp,rolling_sum_kickReturnYards20_opp,rolling_sum_kickingPoints20_opp,rolling_sum_netPassingYards20_opp,rolling_sum_passesDeflected20_opp,rolling_sum_passesIntercepted20_opp,rolling_sum_passingTDs20_opp,rolling_sum_puntReturns20_opp,rolling_sum_qbHurries20_opp,rolling_sum_rushingAttempts20_opp,rolling_sum_rushingTDs20_opp,rolling_sum_rushingYards20_opp,rolling_sum_sacks20_opp,rolling_sum_tacklesForLoss20_opp,rolling_sum_totalFumbles20_opp,rolling_sum_totalPenaltiesYards20_opp,rolling_sum_totalYards20_opp,rolling_sum_turnovers20_opp,rolling_sum_yardsPerPass20_opp,rolling_sum_yardsPerRushAttempt20_opp,rolling_sum_totalTDs20_opp,rolling_sum_Points8_opp,rolling_sum_firstDowns8_opp,rolling_sum_fumblesLost8_opp,rolling_sum_fumblesRecovered8_opp,rolling_sum_interceptions8_opp,rolling_sum_kickReturnYards8_opp,rolling_sum_kickingPoints8_opp,rolling_sum_netPassingYards8_opp,rolling_sum_passesDeflected8_opp,rolling_sum_passesIntercepted8_opp,rolling_sum_passingTDs8_opp,rolling_sum_puntReturns8_opp,rolling_sum_qbHurries8_opp,rolling_sum_rushingAttempts8_opp,rolling_sum_rushingTDs8_opp,rolling_sum_rushingYards8_opp,rolling_sum_sacks8_opp,rolling_sum_tacklesForLoss8_opp,rolling_sum_totalFumbles8_opp,rolling_sum_totalPenaltiesYards8_opp,rolling_sum_totalYards8_opp,rolling_sum_turnovers8_opp,rolling_sum_yardsPerPass8_opp,rolling_sum_yardsPerRushAttempt8_opp,rolling_sum_totalTDs8_opp,talent,talent_opp,SP,SP_opp,Id,HomeTeam,HomeScore,AwayTeam,AwayScore,LineProvider,OverUnder,Spread,FormattedSpread,OpeningSpread,OpeningOverUnder,HomeMoneyline,AwayMoneyline
175,401523994,TCU,Big 12,home,42,1,2023,24.42,0.0,27.0,1.2,0.0,1.0,NaN,NaN,2.0,0.0,150.0,5.0,6.0,279.0,2.0,NaN,2.0,25.27,NaN,NaN,NaN,2.0,37.0,4.0,262.0,4.0,44.0,7.0,10.17,1.0,10.78,541.0,2.0,6.6,7.1,6.0,Colorado,Pac-12,away,45,1,2023,38.47,0.0,30.0,2.2,1.0,0.0,0.0,0.0,0.0,0.0,18.0,1.0,9.0,510.0,3.0,2.0,4.0,34.33,0.0,2.0,1.0,2.0,34.0,2.0,55.0,0.0,46.0,0.0,9.15,1.0,6.35,565.0,1.0,10.9,1.6,6.0,-3,87,False,676.0,420.0,12.0,8.0,8.0,1182.2,154.0,5338.0,76.0,18.0,40.0,29.0,35.0,764.0,40.0,3748.0,35.0,97.0,23.0,123.052,9086.0,20.0,8.995,4.940,85.0,292.0,171.0,4.0,4.0,3.0,460.0,74.0,2050.0,37.0,9.0,17.0,17.0,10.0,323.0,16.0,1449.0,16.0,41.0,7.0,38.75,3499.0,7.0,8.4125,4.5625,36.0,386.0,322.0,14.0,11.0,11.0,1243.0,114.0,3658.0,51.0,16.0,22.0,22.0,41.0,668.0,18.0,2173.0,18.0,84.0,31.0,123.630,5831.0,25.0,6.140,3.190,44.0,163.0,140.0,8.0,4.0,8.0,601.0,43.0,1765.0,17.0,7.0,10.0,8.0,15.0,261.0,9.0,790.0,6.0,31.0,18.0,52.390,2555.0,16.0,6.7375,3.0000,20.0,768.25,711.87,7.9,-4.9,401523994.0,TCU,42.0,Colorado,45.0,DraftKings,63.5,20.5,TCU -20.5,-20.0,59.0,-1350.0,850.0
176,401525832,TCU,Big 12,home,41,2,2023,28.33,NaN,22.0,2.4,1.0,1.0,0.0,0.0,1.0,0.0,64.0,3.0,11.0,313.0,NaN,1.0,3.0,24.34,1.0,68.0,5.0,NaN,37.0,1.0,129.0,NaN,NaN,NaN,4.12,2.0,5.50,442.0,2.0,9.5,3.5,5.0,Nicholls,Southland,away,6,2,2023,17.36,NaN,15.0,0.2,1.0,1.0,0.0,0.0,1.0,0.0,56.0,3.0,6.0,177.0,NaN,1.0,0.0,35.26,0.0,6.0,1.0,NaN,39.0,0.0,86.0,NaN,NaN,NaN,8.20,1.0,7.45,263.0,2.0,4.9,2.2,0.0,35,47,True,687.0,426.0,11.0,9.0,10.0,1215.2,153.0,5271.0,77.0,18.0,38.0,28.0,37.0,764.0,44.0,3827.0,37.0,98.0,23.0,124.731,9098.0,21.0,8.750,5.050,87.0,291.0,171.0,3.0,5.0,5.0,529.0,67.0,2043.0,33.0,8.0,17.0,13.0,10.0,317.0,17.0,1487.0,18.0,43.0,6.0,45.13,3530.0,8.0,8.3375,4.8000,37.0,348.0,382.0,11.0,4.0,24.0,1102.0,98.0,4139.0,17.0,8.0,21.0,23.0,8.0,716.0,19.0,2778.0,18.0,50.0,19.0,102.022,6917.0,35.0,6.440,3.820,41.0,149.0,167.0,6.0,1.0,11.0,547.0,45.0,1576.0,0.0,6.0,8.0,10.0,0.0,317.0,8.0,1210.0,0.0,0.0,7.0,35.850,2786.0,17.0,6.0625,3.8125,17.0,768.25,57.04,7.9,NaN,401525832.0,TCU,41.0,Nicholls,6.0,William Hill (New Jersey),59.5,41.5,TCU -41.5,NaN,NaN,NaN,NaN
177,401525836,TCU,Big 12,away,36,3,2023,24.37,0.0,35.0,2.3,1.0,0.0,0.0,1.0,1.0,0.0,28.0,1.0,12.0,314.0,1.0,2.0,2.0,34.16,0.0,0.0,1.0,3.0,51.0,2.0,250.0,6.0,41.0,8.0,6.15,1.0,7.75,564.0,2.0,8.5,4.9,4.0,Houston,Big 12,home,13,3,2023,17.35,1.0,12.0,0.4,0.0,1.0,0.0,35.0,2.0,1.0,201.0,6.0,7.0,225.0,5.0,1.0,0.0,25.44,0.0,0.1,1.0,3.0,27.0,0.0,41.0,3.0,50.0,6.0,4.15,0.0,7.60,266.0,2.0,6.4,1.5,1.0,23,49,True,711.0,429.0,11.0,10.0,9.0,1171.2,159.0,5340.0,76.0,19.0,40.0,33.0,36.0,767.0,45.0,3807.0,36.0,95.0,22.0,122.781,9147.0,20.0,8.755,5.005,90.0,294.0,168.0,4.0,6.0,6.0,558.0,70.0,2076.0,31.0,7.0,17.0,18.0,7.0,298.0,16.0,1401.0,18.0,40.0,7.0,47.33,3477.0,10.0,8.1750,4.7625,37.0,704.0,464.0,9.0,11.0,17.0,1379.0,150.0,6022.0,77.0,19.0,53.0,24.0,38.0,667.0,33.0,2959.0,43.0,128.0,19.0,151.833,8981.0,26.0,8.280,4.640,90.0,291.0,191.0,2.0,4.0,9.0,667.0,55.0,2743.0,28.0,5.0,24.0,8.0,12.0,218.0,13.0,1006.0,14.0,45.0,7.0,53.290,3749.0,11.0,8.0375,4.9750,39.0,768.25,670.25,7.9,-7.8,401525836.0,Houston,13.0,TCU,36.0,Bovada,64.0,7.0,TCU -7.0,8.0,62.0,260.0,-320.0
178,401525849,TCU,Big 12,home,34,4,2023,24.33,0.0,25.0,3.5,0.0,0.0,0.0,53.0,0.0,0.0,22.0,1.0,10.0,265.0,6.0,2.0,3.0,29.48,NaN,NaN,NaN,4.0,44.0,1.0,192.0,3.0,31.0,5.0,6.15,NaN,6.48,457.0,0.0,8.0,4.4,4.0,SMU,American Athletic,away,17,4,2023,16.35,0.0,21.0,1.3,0.0,0.0,NaN,NaN,2.0,0.0,5.0,1.0,5.0,258.0,1.0,NaN,0.0,30.12,NaN,NaN,NaN,2.0,39.0,2.0,158.0,2.0,46.0,6.0,5.15,NaN,4.20,416.0,2.0,7.4,4.1,2.0,17,51,True,735.0,447.0,10.0,10.0,10.0,1132.2,167.0,5470.0,74.0,20.0,42.0,32.0,37.0,777.0,46.0,3901.0,40.0,97.0,20.0,124.081,9371.0,20.0,8.850,5.060,93.0,289.0,186.0,4.0,4.0,6.0,518.0,71.0,2049.0,29.0,8.0,16.0,18.0,10.0,322.0,16.0,1498.0,21.0,44.0,7.0,48.41,3547.0,10.0,7.7125,4.6625,36.0,721.0,486.0,13.0,13.0,18.0,700.0,153.0,6060.0,54.0,13.0,52.0,24.0,40.0,727.0,39.0,3062.0,48.0,109.0,29.0,109.105,9122.0,31.0,8.145,4.215,92.0,311.0,206.0,4.0,1.0,6.0,229.0,63.0,2444.0,17.0,6.0,26.0,9.0,15.0,321.0,13.0,1451.0,17.0,39.0,10.0,36.960,3895.0,10.0,8.7000,4.4750,40.0,768.25,714.21,7.9,10.1,401525849.0,TCU,34.0,SMU,17.0,DraftKings,62.0,6.5,TCU -6.5,-6.5,64.0,-270.0,225.0
179,401525853,TCU,Big 12,home,21,5,2023,23.41,0.0,23.0,1.2,0.0,0.0,NaN,NaN,0.0,0.0,43.0,2.0,3.0,298.0,4.0,NaN,2.0,26.33,0.0,1.0,2.0,0.0,38.0,1.0,135.0,0.0,32.0,5.0,6.16,1.0,7.39,433.0,0.0,7.3,3.6,3.0,West Virginia,Big 12,away,24,5,2023,10.21,0.0,20.0,1.3,0.0,0.0,NaN,NaN,0.0,0.0,18.0,1.0,6.0,142.0,6.0,NaN,0.0,33.27,0.0,32.0,2.0,5.0,43.0,3.0,201.0,5.0,45.0,9.0,4.13,1.0,2.10,343.0,0.0,6.8,4.7,3.0,-3,45,False,739.0,445.0,9.0,10.0,10.0,1154.2,165.0,5267.0,79.0,20.0,43.0,31.0,39.0,786.0,46.0,3999.0,42.0,95.0,18.0,117.450,9266.0,19.0,8.695,5.145,94.0,289.0,187.0,4.0,4.0,6.0,485.0,71.0,2119.0,27.0,9.0,17.0,15.0,12.0,315.0,16.0,1456.0,20.0,40.0,7.0,50.37,3575.0,10.0,7.6500,4.6375,36.0,581.0,444.0,11.0,11.0,17.0,589.0,131.0,4242.0,61.0,12.0,34.0,27.0,55.0,790.0,37.0,3513.0,42.0,122.0,20.0,113.980,7755.0,28.0,6.450,4.340,73.0,210.0,158.0,4.0,1.0,6.0,226.0,40.0,1274.0,36.0,6.0,10.0,15.0,24.0,353.0,17.0,1565.0,20.0,57.0,6.0,41.240,2839.0,10.0,6.2000,4.4625,28.0,768.25,666.23,7.9,7.5,401525853.0,TCU,21.0,West Virginia,24.0,DraftKings,52.0,12.5,TCU -12.5,-10.5,51.0,-470.0,360.0
180,401525859,TCU,Big 12,away,14,6,2023,21.36,0.0,23.0,1.3,0.0,0.0,NaN,NaN,4.0,0.0,130.0,5.0,2.0,213.0,4.0,NaN,2.0,27.42,0.0,13.0,1.0,2.0,37.0,0.0,185.0,0.0,41.0,4.0,7.14,1.0,6.52,398.0,4.0,5.9,5.0,2.0,Iowa State,Big 12,home,27,6,2023,16.28,0.0,16.0,1.1,0.0,0.0,0.0,9.0,0.0,NaN,NaN,NaN,9.0,138.0,3.0,4.0,1.0,32.18,0.0,5.0,1.0,4.0,37.0,2.0,215.0,2.0,39.0,5.0,5.15,NaN,1.15,353.0,0.0,4.9,5.8,3.0,-13,41,False,743.0,456.0,9.0,8.0,10.0,1119.2,163.0,5400.0,81.0,20.0,45.0,33.0,38.0,792.0,46.0,4026.0,42.0,98.0,18.0,112.050,9426.0,19.0,8.665,5.155,96.0,293.0,191.0,3.0,4.0,6.0,508.0,69.0,2293.0,24.0,8.0,18.0,14.0,12.0,309.0,16.0,1432.0,18.0,39.0,7.0,52.27,3725.0,9.0,8.0250,4.6375,37.0,442.0,386.0,8.0,14.0,22.0,545.0,122.0,4953.0,69.0,19.0,33.0,29.0,78.0,631.0,19.0,2314.0,37.0,111.0,21.0,111.690,7267.0,30.0,6.760,3.760,53.0,155.0,135.0,1.0,1.0,7.0,204.0,47.0,1705.0,35.0,10.0,12.0,10.0,46.0,253.0,5.0,985.0,13.0,40.0,4.0,45.690,2690.0,8.0,6.6250,3.9000,18.0,768.25,638.87,7.9,7.5,401525859.0,Iowa State,27.0,TCU,14.0,DraftKings,53.0,6.5,TCU -6.5,5.5,49.5,200.0,-245.0
181,401525865,TCU,Big 12,home,44,7,2023,38.59,1.0,30.0,0.1,0.0,1.0,1.0,35.0,2.0,0.0,50.0,3.0,14.0,447.0,2.0,1.0,4.0,30.38,0.0,2.0,2.0,0.0,27.0,0.0,137.0,3.0,38.0,5.0,12.19,1.0,7.59,584.0,2.0,7.6,5.1,5.0,BYU,Big 12,away,11,7,2023,15.34,0.0,15.0,1.3,1.0,0.0,0.0,17.0,1.0,0.0,91.0,4.0,3.0,152.0,5.0,2.0,0.0,29.22,0.0,0.0,1.0,0.0,32.0,1.0,91.0,0.0,53.0,0.0,2.14,1.0,5.50,243.0,2.0,4.5,2.8,1.0,33,55,True,726.0,460.0,8.0,8.0,13.0,1249.0,158.0,5447.0,81.0,19.0,47.0,33.0,38.0,780.0,42.0,3885.0,40.0,99.0,16.0,115.200,9332.0,21.0,8.440,5.070,94.0,278.0,194.0,3.0,4.0,9.0,618.0,66.0,2179.0,26.0,7.0,19.0,12.0,14.0,319.0,13.0,1502.0,17.0,36.0,8.0,55.44,3681.0,12.0,7.6250,4.7250,35.0,618.0,423.0,6.0,8.0,12.0,764.0,120.0,5218.0,68.0,17.0,47.0,26.0,35.0,648.0,31.0,2873.0,20.0,77.0,21.0,119.081,8091.0,18.0,8.140,4.160,81.0,253.0,159.0,4.0,3.0,5.0,412.0,47.0,1980.0,32.0,9.0,18.0,13.0,19.0,261.0,15.0,983.0,10.0,28.0,8.0,43.542,2963.0,9.0,8.0500,3.2625,34.0,768.25,576.25,7.9,-3.3,401525865.0,TCU,44.0,BYU,11.0,DraftKings,52.5,5.0,TCU -5,-5.0,52.0,-205.0,170.0
182,401525870,TCU,Big 12,away,3,8,2023,23.43,0.0,19.0,2.3,0.0,0.0,NaN,NaN,1.0,0.0,32.0,2.0,3.0,187.0,1.0,NaN,0.0,21.10,NaN,NaN,NaN,2.0,22.0,0.0,113.0,1.0,44.0,4.0,2.13,NaN,4.33,300.0,1.0,4.3,5.1,0.0,Kansas State,Big 12,home,41,8,2023,15.26,0.0,29.0,0.1,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,11.0,244.0,6.0,1.0,4.0,38.50,0.0,5.0,1.0,2.0,52.0,1.0,343.0,2.0,35.0,2.0,10.13,1.0,6.45,587.0,0.0,9.4,6.6,5.0,-38,44,False,756.0,472.0,8.0,9.0,14.0,1184.0,170.0,5678.0,80.0,20.0,49.0,35.0,37.0,768.0,42.0,3890.0,42.0,101.0,17.0,118.550,9568.0,22.0,8.405,5.155,97.0,260.0,203.0,3.0,4.0,11.0,563.0,66.0,2380.0,22.0,6.0,19.0,13.0,11.0,308.0,11.0,1508.0,19.0,37.0,8.0,56.46,3888.0,14.0,7.5500,4.9375,32.0,690.0,433.0,6.0,15.0,11.0,934.0,158.0,4431.0,62.0,22.0,35.0,25.0,42.0,820.0,50.0,4354.0,46.0,114.0,20.0,112.920,8785.0,17.0,7.855,5.275,88.0,289.0,190.0,1.0,3.0,7.0,335.0,59.0,1893.0,27.0,7.0,16.0,12.0,14.0,334.0,22.0,1834.0,19.0,49.0,4.0,43.710,3727.0,8.0,7.7250,5.4250,38.0,768.25,616.00,7.9,16.2,401525870.0,Kansas State,41.0,TCU,3.0,DraftKings,60.5,-6.0,Kansas State -6,-4.5,NaN,-230.0,190.0
183,401525879,TCU,Big 12,away,28,10,2023,32.52,0.0,26.0,2.2,0.0,0.0,NaN,NaN,2.0,0.0,31.0,2.0,4.0,353.0,2.0,NaN,1.0,25.35,NaN,NaN,NaN,2.0,26.0,3.0,87.0,2.0,50.0,8.0,10.18,NaN,5.41,440.0,2.0,6.8,3.3,4.0,Texas Tech,Big 12,home,35,10,2023,28.36,0.0,22.0,2.3,0.0,0.0,0.0,23.0,0.0,NaN,NaN,NaN,9.0,282.0,1.0,2.0,2.0,34.25,0.0,29.0,1.0,4.0,42.0,2.0,146.0,0.0,43.0,1.0,7.18,NaN,8.72,428.0,0.0,7.8,3.5,4.0,-7,63,False,721.0,474.0,8.0,9.0,15.0,1216.0,165.0,5727.0,74.0,20.0,49.0,32.0,34.0,760.0,38.0,3728.0,41.0,99.0,17.0,115.280,9455.0,23.0,8.320,4.950,92.0,235.0,204.0,2.0,3.0,11.0,519.0,61.0,2316.0,20.0,6.0,18.0,11.0,13.0,293.0,9.0,1403.0,17.0,38.0,7.0,56.34,3719.0,13.0,7.2125,4.8375,29.0,615.0,490.0,9.0,14.0,28.0,1018.0,151.0,5346.0,55.0,14.0,38.0,23.0,64.0,785.0,35.0,3250.0,41.0,113.5,24.0,124.090,8596.0,37.0,6.485,4.140,76.0,242.0,175.0,4.0,1.0,11.0,449.0,52.0,1795.0,19.0,7.0,16.0,11.0,18.0,303.0,12.0,1461.0,14.0,38.0,8.0,48.720,3256.0,15.0,6.4375,4.9250,31.0,768.25,694.26,7.9,6.1,401525879.0,Texas Tech,35.0,TCU,28.0,DraftKings,59.5,-2.5,Texas Tech -2.5,-3.0,59.5,-142.0,120.0
184,401525891,TCU,Big 12,home,26,11,2023,24.36,0.0,21.0,1.2,1.0,0.0,0.0,40.0,1.0,NaN,NaN,NaN,8.0,302.0,1.0,1.0,2.0,25.42,0.0,29.0,2.0,2.0,28.0,1.0,88.0,0.0,44.0,3.0,3.11,2.0,6.51,390.0,2.0,8.4,3.1,3.0,Texas,Big 12,away,29,11,2023,22.33,0.0,22.0,0.1,0.0,1.0,0.0,2.0,1.0,0.0,15.0,1.0,11.0,317.0,2.0,1.0,1.0,34.18,NaN,NaN,NaN,1.0,41.0,2.0,165.0,3.0,37.0,6.0,4.13,1.0,7.59,482.0,1.0,9.6,4.0,3.0,-3,55,False,690.0,472.0,7.0,9.0,17.0,1202.0,160.0,5630.0,70.0,18.0,45.0,32.0,31.0,749.0,38.0,3635.0,43.0,104.0,16.0,117.490,9265.0,24.0,8.000,4.870,88.0,221.0,203.0,2.0,2.0,11.0,400.0,59.0,2390.0,20.0,6.0,17.0,11.0,13.0,282.0,8.0,1228.0,15.0,39.0,6.0,50.97,3618.0,13.0,7.2375,4.3625,27.0,695.0,447.0,13.0,13.0,13.0,663.0,185.0,4986.0,71.0,19.0,36.0,30.0,61.0,772.0,44.0,4015.0,45.0,136.0,21.0,130.779,9001.0,26.0,8.220,5.050,84.0,267.0,170.0,6.0,5.0,7.0,265.0,75.0,2109.0,29.0,7.0,11.0,18.0,31.0,306.0,18.0,1572.0,18.0,54.0,10.0,53.900,3681.0,13.0,8.5375,5.1125,32.0,768.25,913.24,7.9,23.2,401525891.0,TCU,26.0,Texas,29.0,DraftKings,NaN,-6.0,Texas -6,6.0,NaN,410.0,-550.0
185,401525897,TCU,Big 12,home,42,12,2023,26.33,0.0,24.0,0.2,1.0,0.0,NaN,NaN,0.0,0.0,85.0,4.0,6.0,431.0,2.0,NaN,2.0,26.32,0.0,39.0,2.0,2.0,30.0,4.0,100.0,1.0,41.0,6.0,9.11,1.0,4.35,531.0,1.0,13.1,3.3,6.0,Baylor,Big 12,away,17,12,2023,21.31,0.0,20.0,2.6,0.0,1.0,NaN,NaN,0.0,0.0,23.0,1.0,5.0,199.0,3.0,NaN,1.0,33.28,NaN,NaN,NaN,1.0,40.0,1.0,148.0,1.0,36.0,5.0,5.14,0.0,1.90,347.0,0.0,6.4,3.7,2.0,25,59,True,674.0,472.0,8.0,9.0,18.0,1117.0,162.0,5636.0,67.0,17.0,44.0,33.0,31.0,742.0,36.0,3532.0,40.0,100.0,17.0,113.060,9168.0,26.0,7.925,4.750,85.0,206.0,202.0,2.0,1.0,11.0,336.0,56.0,2379.0,21.0,6.0,16.0,8.0,15.0,273.0,8.0,1187.0,15.0,42.0,6.0,51.98,3566.0,13.0,7.1000,4.3125,25.0,518.0,431.0,13.0,14.0,17.0,1107.0,124.0,5103.0,67.0,20.0,27.0,20.0,38.0,755.0,32.0,2884.0,36.0,99.0,20.0,80.560,7987.0,30.0,7.215,3.670,60.0,172.0,159.0,6.0,7.0,4.0,485.0,46.0,2186.0,24.0,5.0,11.0,11.0,11.0,267.0,7.0,760.0,11.0,36.0,11.0,30.830,2946.0,10.0,6.8750,2.7625,18.0,768.25,678.00,7.9,-8.3,401525897.0,TCU,42.0,Baylor,17.0,DraftKings,58.5,12.0,TCU -12,-4.0,NaN,-535.0,400.0
186,401525900,TCU,Big 12,away,45,13,2023,32.58,0.0,25.0,1.3,0.0,1.0,0.0,0.0,1.0,0.0,65.0,4.0,7.0,344.0,5.0,1.0,4.0,30.22,NaN,NaN,NaN,1.0,29.0,2.0,176.0,2.0,35.0,5.0,7.16,1.0,7.82,520.0,1.0,5.9,6.1,6.0,Oklahoma,Big 12,home,69,13,2023,24.38,1.0,30.0,2.2,1.0,0.0,1.0,45.0,1.0,0.0,22.0,1.0,15.0,400.0,6.0,1.0,3.0,29.38,0.0,2.0,2.0,7.0,41.0,5.0,207.0,1.0,40.0,5.0,8.14,1.0,5.46,607.0,2.0,10.5,5.0,9.0,-24,114,False,661.0,467.0,9.0,8.0,18.0,1183.0,161.0,5760.0,66.0,17.0,43.0,34.0,30.0,731.0,35.0,3271.0,37.0,99.0,18.0,112.860,9031.0,27.0,8.130,4.475,83.0,212.0,191.0,2.0,1.0,10.0,393.0,50.0,2496.0,22.0,4.0,16.0,9.0,14.0,252.0,10.0,1037.0,10.0,40.0,6.0,48.58,3533.0,12.0,7.6750,4.1125,27.0,752.0,491.0,13.0,12.0,14.0,829.0,158.0,5802.0,69.0,32.0,46.0,26.0,78.0,846.0,47.0,3841.0,31.0,145.0,22.0,127.591,9643.0,27.0,8.395,4.540,98.0,331.0,203.0,6.0,4.0,5.0,299.0,71.0,2466.0,33.0,11.0,18.0,14.0,42.0,329.0,22.0,1536.0,12.0,55.0,11.0,53.181,4002.0,11.0,8.9625,4.6875,43.0,768.25,884.97,7.9,15.0,401525900.0,Oklahoma,69.0,TCU,45.0,DraftKings,NaN,-12.5,Oklahoma -12.5,-6.5,NaN,-425.0,330.0

In [100]:
for team, teamDF in teamDict.items():
    teamDict[team] = teamDF[teamDF.columns.drop(list(teamDF.filter(regex='Unnamed')))]

In [98]:
files = glob.glob(os.path.join('/users/blaizelahman/Desktop/CFB Model/Updated Data', '*'))

for file in files:
        
    try:
            
        os.remove(file)
        print(f"Deleted {file}")
            
    except Exception as e:
        
        print(f"Could not delete {file}: {e}")

Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Western_Michigan_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Memphis_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Arkansas_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Wake_Forest_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Texas_State_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Liberty_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Temple_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Auburn_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Miami_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Alabama_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Louisville_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Washington_State_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/North_Texas_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Washington_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Virginia_Tech_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Texas_A&M_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Buffalo_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Ohio_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Minnesota_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Syracuse_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Southern_Mississippi_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Ole_Miss_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Idaho_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Western_Kentucky_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Utah_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Stanford_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Georgia_State_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Utah_State_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/West_Virginia_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Nevada_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Louisiana_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Mississippi_State_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Boston_College_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Michigan_State_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Miami_(OH)_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Georgia_Southern_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UT_San_Antonio_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Pittsburgh_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Nebraska_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Clemson_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Troy_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Coastal_Carolina_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Arizona_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Kent_State_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UTEP_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Toledo_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UCLA_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Louisiana_Monroe_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Oregon_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Oklahoma_State_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Kansas_State_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Middle_Tennessee_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/South_Florida_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/USC_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/South_Alabama_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Hawai'i_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Bowling_Green_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Penn_State_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Fresno_State_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Boise_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/New_Mexico_State_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Navy_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Florida_Atlantic_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Arizona_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/South_Carolina_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Virginia_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Rice_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Marshall_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Tulane_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Tulsa_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/California_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UNLV_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Texas_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Georgia_Tech_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Connecticut_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/TCU_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Oregon_State_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Maryland_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/New_Mexico_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Rutgers_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Wisconsin_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Iowa_State_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Appalachian_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Texas_Tech_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Air_Force_updated_model 11.34.21 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/NC_State_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/SMU_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/San_José_State_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Colorado_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Florida_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Georgia_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UAB_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Central_Michigan_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Louisiana_Tech_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Eastern_Michigan_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Baylor_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Iowa_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/BYU_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Florida_International_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Cincinnati_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Michigan_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Florida_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Charlotte_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Wyoming_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Notre_Dame_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Kansas_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Purdue_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/LSU_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Ball_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Arkansas_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Vanderbilt_updated_model 11.34.28 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Ohio_State_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Indiana_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Duke_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Colorado_State_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UMass_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Oklahoma_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Northwestern_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Northern_Illinois_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Houston_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Kentucky_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/UCF_updated_model 11.34.27 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Missouri_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Old_Dominion_updated_model 11.34.25 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/East_Carolina_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Army_updated_model 11.34.22 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Illinois_updated_model 11.34.23 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/North_Carolina_updated_model 11.34.24 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Akron_updated_model 11.34.21 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/San_Diego_State_updated_model 11.34.26 PM.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Updated Data/Tennessee_updated_model 11.34.27 PM.csv

In [102]:
for key, team in teamDict.items():
    if 2023 in team['Year'].values:
        name = key.replace(' ', '_') + '_updated_model.csv'
        path = os.path.join('/users/blaizelahman/Desktop/CFB Model/Updated Data', name)
        team.to_csv(path)
        print('CSV: ' + name)

CSV: Western_Michigan_updated_model.csv
CSV: Memphis_updated_model.csv
CSV: Arkansas_updated_model.csv
CSV: Wake_Forest_updated_model.csv
CSV: Texas_State_updated_model.csv
CSV: Temple_updated_model.csv
CSV: Auburn_updated_model.csv
CSV: Miami_updated_model.csv
CSV: Alabama_updated_model.csv
CSV: Louisville_updated_model.csv
CSV: Washington_State_updated_model.csv
CSV: North_Texas_updated_model.csv
CSV: Washington_updated_model.csv
CSV: Virginia_Tech_updated_model.csv
CSV: Texas_A&M_updated_model.csv
CSV: Buffalo_updated_model.csv
CSV: Ohio_updated_model.csv
CSV: Minnesota_updated_model.csv
CSV: Syracuse_updated_model.csv
CSV: Southern_Mississippi_updated_model.csv
CSV: Ole_Miss_updated_model.csv
CSV: Idaho_updated_model.csv
CSV: Western_Kentucky_updated_model.csv
CSV: Utah_updated_model.csv
CSV: Stanford_updated_model.csv
CSV: Georgia_State_updated_model.csv
CSV: Utah_State_updated_model.csv
CSV: West_Virginia_updated_model.csv
CSV: Nevada_updated_model.csv
CSV: Louisiana_updated_model.csv
CSV: Mississippi_State_updated_model.csv
CSV: Boston_College_updated_model.csv
CSV: Michigan_State_updated_model.csv
CSV: Miami_(OH)_updated_model.csv
CSV: Georgia_Southern_updated_model.csv
CSV: UT_San_Antonio_updated_model.csv
CSV: Pittsburgh_updated_model.csv
CSV: Nebraska_updated_model.csv
CSV: Clemson_updated_model.csv
CSV: Troy_updated_model.csv
CSV: Arizona_State_updated_model.csv
CSV: Kent_State_updated_model.csv
CSV: UTEP_updated_model.csv
CSV: Toledo_updated_model.csv
CSV: UCLA_updated_model.csv
CSV: Louisiana_Monroe_updated_model.csv
CSV: Oregon_updated_model.csv
CSV: Oklahoma_State_updated_model.csv
CSV: Kansas_State_updated_model.csv
CSV: Middle_Tennessee_updated_model.csv
CSV: South_Florida_updated_model.csv
CSV: USC_updated_model.csv
CSV: South_Alabama_updated_model.csv
CSV: Hawai'i_updated_model.csv
CSV: Bowling_Green_updated_model.csv
CSV: Penn_State_updated_model.csv
CSV: Fresno_State_updated_model.csv
CSV: Boise_State_updated_model.csv
CSV: New_Mexico_State_updated_model.csv
CSV: Navy_updated_model.csv
CSV: Florida_Atlantic_updated_model.csv
CSV: Arizona_updated_model.csv
CSV: South_Carolina_updated_model.csv
CSV: Virginia_updated_model.csv
CSV: Rice_updated_model.csv
CSV: Marshall_updated_model.csv
CSV: Tulane_updated_model.csv
CSV: Tulsa_updated_model.csv
CSV: California_updated_model.csv
CSV: UNLV_updated_model.csv
CSV: Texas_updated_model.csv
CSV: Georgia_Tech_updated_model.csv
CSV: Connecticut_updated_model.csv
CSV: TCU_updated_model.csv
CSV: Oregon_State_updated_model.csv
CSV: Maryland_updated_model.csv
CSV: New_Mexico_updated_model.csv
CSV: Rutgers_updated_model.csv
CSV: Wisconsin_updated_model.csv
CSV: Iowa_State_updated_model.csv
CSV: Appalachian_State_updated_model.csv
CSV: Texas_Tech_updated_model.csv
CSV: Air_Force_updated_model.csv
CSV: NC_State_updated_model.csv
CSV: SMU_updated_model.csv
CSV: San_José_State_updated_model.csv
CSV: Colorado_updated_model.csv
CSV: Florida_updated_model.csv
CSV: Georgia_updated_model.csv
CSV: UAB_updated_model.csv
CSV: Central_Michigan_updated_model.csv
CSV: Louisiana_Tech_updated_model.csv
CSV: Eastern_Michigan_updated_model.csv
CSV: Baylor_updated_model.csv
CSV: Iowa_updated_model.csv
CSV: BYU_updated_model.csv
CSV: Florida_International_updated_model.csv
CSV: Cincinnati_updated_model.csv
CSV: Michigan_updated_model.csv
CSV: Florida_State_updated_model.csv
CSV: Charlotte_updated_model.csv
CSV: Wyoming_updated_model.csv
CSV: Notre_Dame_updated_model.csv
CSV: Kansas_updated_model.csv
CSV: Purdue_updated_model.csv
CSV: LSU_updated_model.csv
CSV: Ball_State_updated_model.csv
CSV: Arkansas_State_updated_model.csv
CSV: Vanderbilt_updated_model.csv
CSV: Ohio_State_updated_model.csv
CSV: Indiana_updated_model.csv
CSV: Duke_updated_model.csv
CSV: Colorado_State_updated_model.csv
CSV: UMass_updated_model.csv
CSV: Oklahoma_updated_model.csv
CSV: Northwestern_updated_model.csv
CSV: Northern_Illinois_updated_model.csv
CSV: Houston_updated_model.csv
CSV: Kentucky_updated_model.csv
CSV: UCF_updated_model.csv
CSV: Missouri_updated_model.csv
CSV: Old_Dominion_updated_model.csv
CSV: East_Carolina_updated_model.csv
CSV: Army_updated_model.csv
CSV: Illinois_updated_model.csv
CSV: North_Carolina_updated_model.csv
CSV: Akron_updated_model.csv
CSV: San_Diego_State_updated_model.csv
CSV: Tennessee_updated_model.csv